// src/routes/+page.svelte
<script lang="ts">
	import Background from '$components/Background.svelte';
</script>

<svelte:head>
	<title>Brown Dog Biscuits</title>
	<meta name="description" content="Fresh made dog treats" />
</svelte:head>

<section class="relative h-full">
	<Background />
	<div class="z-10"></div>
</section>

// apps/brown-dog-biscuits/src/routes/index.tsx
import { component$ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import { Link } from '@builder.io/qwik-city';
export default component$(() => {
  return <div></div>;
});

export const head: DocumentHead = {
  title: 'Brown Dog Biscuits',
  meta: [
    {
      name: 'description',
      content: 'Fresh baked dog treats!',
    },
  ],
};
